### PR TITLE
Attempted to remove object dependency

### LINKED ISSUE #38: Objects have properties that they shouldn't have.
- Player object shouldn't have a property to see if the Wumpus is Alive, that should be in a Wumpus object or in the GameLocation object.
- Wumpus object should not have the property for GameLocation
- GameLocation should not have the property for Cave 
- GameLocation should not have the property for Random, just initialize random in the function that needs it

The GameController should be the one that's talking across the classes (objects) not the classes (objects) themselves

### PR DESCRIPTION
**Pull request by ZestyTS**
This is an attempt to fix #38 but after digging in the code, I see what the real issue is which might take too long to fix. I couldn't update all objects because it would take too long and might stomp a lot of code. Essentially functions are doing more than they should, so you're having to pass parameters into functions that they shouldn't have. I'm going to leave an explanation below this so you can see what I mean, but you can honestly ignore this because it won't impact your grade, I just want to bring it to your attention. Lastly, you can accept my PR, or deny it, either is fine.

Looking at GameLocation's ShootArrow function, you can kind of see what I mean.
image

ShootArrow checks to see if the arrow would hit the Wumpus which is correct, but it also either ends the game or makes the Wumpus move, which is a bit more than just shooting an arrow. The name should match what it does, in this case it would be "ChecksToSeeIfArrowHitsAndDecidesIfTheGameIsOverOrIfWumpusIsMoving" if we look at it like that then it might make sense to have three different functions named something like
"bool ArrowHit"
"void GameOver(true)"
"void WumpusMove"

Each of these functions would also probably be in different areas with the GameController deciding how everything happens. ArrowHit would be part of GameLocation, GameOver would be part of the GameController, and WumpusMove would be part of the Wumpus object. I have an example in my code if you look, starting at line 173: https://github.com/ZestyTS/HuntTheWumpus/blob/main/HuntTheWumpus/Controller/Game.cs

### CODE REVIEW

**Comment by Perrytheplaty43** [comment]
Great thanks. I don't even remember why those were there. I see the checks failed due to line 56 in Form.cs but ill fix that after the merges.

**Comment by ZestyTS** [comment]
Looks like I failed to commit the other changes I made. I'll do that once I move back over to that computer.

**Comment by Perrytheplaty43** [comment]
Ah ok, no problem.

**Comment by ZestyTS** [comment]
~~I've been busy, but I should be able to fix this around this evening.~~
And just like that, I have some downtime, so I'll make these changes from the webapp.

**Pull request merged**
